"""Stage 0, copy C1: Ferrari's dry grass tufts in front of the rock, Living Worlds V11AM.

The copyist's sketch: the original with every grass pixel removed (filled from its non-grass
neighbours), plus tuft centres found as maxima of the blurred dark-grass density. Everything at
pixel level (the blades) is generated by `grass.paired_blades`.
"""
import sys, numpy as np
from scipy import ndimage as ndi
import lw, sp
from grass import tuft_blades, draw_blade_pairs

X0, Y0, X1, Y1 = 140, 390, 340, 480
DARK, MID, LIT = 49, 50, 51


def sketch():
    d = lw.load("V11AM")
    idx = d["idx"][Y0:Y1, X0:X1].copy()
    g = np.isin(idx, [DARK, MID, LIT])
    # fill grass pixels from nearest non-grass pixel
    _, (iy, ix) = ndi.distance_transform_edt(g, return_indices=True)
    bg = idx[iy, ix]
    dens = ndi.gaussian_filter((idx == DARK).astype(float), 6)
    mx = (dens == ndi.maximum_filter(dens, 17)) & (dens > 0.18)
    cy, cx = np.nonzero(mx)
    return d, idx, bg, list(zip(cx, cy, dens[cy, cx]))


def paint(seed=0, params=None):
    d, idx, bg, centres = sketch()
    p = dict(n_per=34, len_mu=34, len_sd=11, spread=0.45, bend=1.4, lit_side=1, tipdark=0.15,
             width=22, wander=0.6, low_mid=0.45, low_dark=0.25)
    if params:
        p.update(params)
    rng = np.random.default_rng(seed)
    out = bg.copy()
    H, W = out.shape
    for cx, cy, dn in centres:
        # base sits below the density centre (tufts are fountains from the ground)
        base_y = min(H + 6, cy + 14)
        n = int(p["n_per"] * (0.6 + dn * 2.0))
        blades = tuft_blades(cx, base_y, n, rng, len_mu=p["len_mu"], len_sd=p["len_sd"],
                             spread=p["spread"], bend=p["bend"], width=p["width"],
                             wander=p["wander"])
        draw_blade_pairs(out, blades, DARK, MID, LIT, lit_side=p["lit_side"],
                         tipdark=p["tipdark"], rng=rng, low_mid=p["low_mid"],
                         low_dark=p["low_dark"])
    return d, idx, out


if __name__ == "__main__":
    d, idx, out = paint(int(sys.argv[1]) if len(sys.argv) > 1 else 0)
    pal = d["pal"]
    a, b = pal[idx], pal[out]
    k = 4
    top = sp.hstack([sp.upscale(a, k), sp.upscale(b, k)], ["Ferrari V11AM tufts 4x", "copy 4x"])
    ya, xa = 20, 90
    z = 8
    bot = sp.hstack([sp.upscale(a[ya:ya + 60, xa:xa + 90], z), sp.upscale(b[ya:ya + 60, xa:xa + 90], z)],
                    ["Ferrari 8x", "copy 8x"])
    sp.save(top, "stage0/c1_tufts_4x.png")
    sp.save(bot, "stage0/c1_tufts_8x.png")
